In [4]:
# Perform various operation in array
import numpy as np

nt = np.array([2,7,9])

print(nt + 5)
print(nt * 3)
print(nt ** 2)
print(nt / 2)
print(nt % 3)
print(nt - 2)
print(nt == 2)
# print(nt = 3) not assigned

[ 7 12 14]
[ 6 21 27]
[ 4 49 81]
[1.  3.5 4.5]
[2 1 0]
[0 5 7]
[ True False False]


In [5]:
# Aggregation functions
s = np.array([3,7,9,13,17])

print(np.sum(s))
print(np.mean(s))
print(np.median(s))
print(np.std(s)) # standard deviation not understand
print(np.min(s))
print(np.max(s))
print(np.var(s)) # variance not understand

# print(np.percentile(s, 25))
# print(np.argmin(s))
# print(np.argmax(s))
# print(np.sort(s))
# print(np.unique(s))
# print(np.unique([1,1,2,2,3,3,4,4,5,5]))
# print(np.unique([1,1,2,2,3,3,4,4,5,5], return_counts=True))
# print(np.unique([1,1,2,2,3,3,4,4,5,5], return_index=True))

49
9.8
9.0
4.833218389437829
3
17
23.36


In [6]:
s = np.array([3,7,9,13,17,19,23])

print(s[::2])
print(s[1:5])

[ 3  9 17 23]
[ 7  9 13 17]


In [7]:
# Positions
t = np.array([[1, 22, 333, 4444], [9999, 777, 33, 11]])
print(f"Positions of t[0,3] is : ", t[0,3])
print(f"Positions of {t[1,0]} is : ", t[1,0])
print(f"Positions of t[0,2] is : ",t[0,2])

print("Sum of t[0,3] + t[1,0] is : ", t[0,3] + t[1,0] )
print()

Positions of t[0,3] is :  4444
Positions of 9999 is :  9999
Positions of t[0,2] is :  333
Sum of t[0,3] + t[1,0] is :  14443



In [ ]:
# Accessing Element

# 1
a = np.array([[[0,1,2,3],[9,7,4,6]] , # 1st array (index no 0)
              [[11,12,14,34],[21,22,43,45]]]) # 2nd array (index no 1)
# Accessing 2nd array (1 index), 
print(a, a.ndim)
print()
print("a[1,1,3] is : ", a[1,1,3]) # 45

[[[ 0  1  2  3]
  [ 9  7  4  6]]

 [[11 12 14 34]
  [21 22 43 45]]] 3

a[1,1,3] is :  45


In [ ]:
# 2
k = np.array([[[0, 1, 2, 3], [9, 7, 4, 6]], 
              [[11, 12, 14, 0], [21, 22, 43, 0]]])  # Add with a 0 to make arrays equal length
print(k, k.ndim)

[[[ 0  1  2  3]
  [ 9  7  4  6]]

 [[11 12 14  0]
  [21 22 43  0]]] 3


In [22]:
# 3
z= [
    [[0, 1, 2, 3], [9, 7, 4, 6]], # 0
    [[11, 12, 14], [21, 22, 43]]] # 1 

print("z[0][1][3] is :",z[1][0][2])
print(z)

z[0][1][3] is : 14
[[[0, 1, 2, 3], [9, 7, 4, 6]], [[11, 12, 14], [21, 22, 43]]]
