In [ ]:
import numpy as np 

# 1 D Array

a1 = np.array([1,3,5,7,9])
a2 = np.array([0,3,2,5,9])

a = np.concatenate((a1,a2))
print("Joining is in One Dimensional :",a)

Joining is in One Dimensional :  [1 3 5 7 9 0 3 2 5 9]


In [9]:
# 2 D Array 

# axis=0 for vertical stacking
# axis=1 for vertical stacking

b1 = np.array([[1,3,5],[2,7,9]])
b2 = np.array([[0,3,2],[0,5,9]])

b = np.concatenate((b1,b2), axis = 0) # axis=0 for vertical stacking
print("Joining is in One Dimensional :\n",b)
print(b.ndim)

b11 = np.array([[1,3,5],[2,7,9]])
b22 = np.array([[0,3,2],[0,5,9]])

bb = np.concatenate((b11,b22), axis = 1) # axis=1 for vertical stacking
print("Joining is in Two Dimensional :\n",bb)
print(bb.ndim)

Joining is in One Dimensional :
 [[1 3 5]
 [2 7 9]
 [0 3 2]
 [0 5 9]]
2
Joining is in Two Dimensional :
 [[1 3 5 0 3 2]
 [2 7 9 0 5 9]]
2


In [ ]:
# axis=0 for vertical stacking

n1 = np.array([[1,3,5],[2,1,3]])
n2 = np.array([[2,4,6],[2,4,5]])

n = np.concatenate((n1,n2),axis = 1) # 0th array join with 0 & 1st array of n1 with 1 st of n2
print(n, n.ndim)

[[1 3 5 2 4 6]
 [2 1 3 2 4 5]] 2


In [20]:
# axis=1 for horizontal stacking

n1 = np.array([[1,3,5],[2,1,3]])
n2 = np.array([[2,4,6],[2,4,5]])

n = np.concatenate((n1,n2),axis = 0) # 0th array join with 0 & 1st array of n1 with 1 st of n2
print(n, n.ndim)

[[1 3 5]
 [2 1 3]
 [2 4 6]
 [2 4 5]] 2


In [28]:
# Stacking Array
# vstack -Vertical stacking
# hstack -Horizontal stacking

n1 = np.array([[1,3,5],[2,1,3]])
n2 = np.array([[2,4,6],[8,9,5]])

n = np.vstack((n1,n2))
print(n, n.ndim)
print()
print(np.vstack((n1,n2)))
print()
print(np.hstack((n2,n1)))

[[1 3 5]
 [2 1 3]
 [2 4 6]
 [8 9 5]] 2

[[1 3 5]
 [2 1 3]
 [2 4 6]
 [8 9 5]]

[[2 4 6 1 3 5]
 [8 9 5 2 1 3]]
