In [4]:
import numpy as np

oned= np.array([1,3,5,7,9])
no = np.delete(oned, 2)
print(no)

[1 3 7 9]


In [13]:
twod = np.array([[19,1,4,3],[3,5,7,9]])
nt = np.delete(twod, 1, axis=0) # Row deleting
print(nt,nt.ndim)

[[19  1  4  3]] 2


In [14]:
twod = np.array([[19,1,4,3],[3,5,7,9]])
nt = np.delete(twod, 1, axis=1) # Column deleting (1,5)
print(nt, nt.ndim)

[[19  4  3]
 [ 3  7  9]] 2
