In [ ]:
# Insert Element 1_D array

import numpy as np

ie = np.array([10, 20, 30, 40, 50, 60])
print("Old Array :",ie)

new_ie = np.insert(ie,4,79)
print("New Array :",new_ie)

Old Array : [10 20 30 40 50 60]
New Array : [10 20 30 40 79 50 60]


In [16]:
# Insert Element 2_D array : Column wise

two_d = np.array([[11,13,17],[7,9,3]])
print(two_d)
print('')
ntd = np.insert(two_d,1,[37,67],axis=1)
print(ntd,ntd.ndim) # Dimension remain same

[[11 13 17]
 [ 7  9  3]]

[[11 37 13 17]
 [ 7 67  9  3]] 2


In [ ]:
# Insert Element 2_D array : Row Wise

two_d = np.array([[11,13,17],[7,9,3]])
print(two_d, two_d.ndim)
print('')
ntd = np.insert(two_d,2,[37,67,53],axis=0)
print(ntd, ntd.ndim) # Dimension remain same

[[11 13 17]
 [ 7  9  3]] 2

[[11 13 17]
 [ 7  9  3]
 [37 67 53]] 2


In [ ]:
# Insert Element 2_D array : None

two_d = np.array([[11,13,17],[7,9,3]])
print(two_d, two_d.ndim)
print('')
ntd = np.insert(two_d,2,[37,67,53],axis=None)
print(ntd, ntd.ndim) # Dimension remain same

[[11 13 17]
 [ 7  9  3]] 2

[11 13 37 67 53 17  7  9  3] 1


In [24]:
# append
d = np.array([11,13,17])
nd = np.append(d,[11,13])
print(nd)

[11 13 17 11 13]
