In [1]:
import numpy as np


In [2]:
zero_arr = np.zeros(3)
print(zero_arr)

[0. 0. 0.]


In [3]:
one = np.ones(3)
print(one)

[1. 1. 1.]


In [ ]:
# ones(shape)
one = np.ones((3,2))
print(one)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# full function : full(shape,value)
full = np.full((3,4),9)
print(full)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
