In [ ]:
# Creating sequence of no in NumPy
# arange(start,stop,jump)
# similar as range & for loop
import numpy as np

x = np.arange(1,20,3)
print(x,) 
# Checking Dimension of thia array
print(x.ndim) 

[ 1  4  7 10 13 16 19]
1


In [ ]:
# identity matrix
# using function eye(value), it is a square matrix which diagonal value should be 1
im = np.eye(3)
print(im)
print(im.ndim)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
2
