In [1]:
import numpy as np 

In [ ]:
# Fancy Indexing
# You can select multiple element at once in a list.
# It only showing elements

ar = np.array([10,20,30,40,50,60])

print(ar[[1,4,2]]) # These are list indexing no

[20 50 30]


In [10]:
# filtering or Boolean Masking
# It only showing/get results with conditions

ar = np.array([10,20,30,40,50,60])
print([ar >= 30])
print(ar >= 30)


[array([False, False,  True,  True,  True,  True])]
[False False  True  True  True  True]


In [ ]:
# Reshaping
# Ravel -converts multidimensional array to 1-D array -it view array
# Flatten - converts multidimensional array to 1-D array -it copy array

rf = np.array([[10,20,30],[40,50,60]])
print(rf)
print("Data Type : ",rf.dtype)
print("Dimensions : ",rf.ndim)
print("Shape of Array : ",rf.shape)

print(rf.ravel()) # View array
print(rf.flatten()) # Copy array

[[10 20 30]
 [40 50 60]]
Data Type :  int64
Dimensions :  2
Shape of Array :  (2, 3)
[10 20 30 40 50 60]
[10 20 30 40 50 60]
